import Foundation
import CryptoKit

/// A delimiter-safe correlation identifier for one native agent approval.
///
/// The first digest scopes the request to a session turn; the second digest
/// identifies the tool request within that turn. Both are 96-bit lowercase
/// hexadecimal prefixes generated by the CLI.
struct AgentApprovalCorrelationID: Hashable, RawRepresentable, Sendable {
    struct Scope: Hashable, RawRepresentable, Sendable {
        let rawValue: String

        init?(rawValue: String) {
            guard AgentApprovalCorrelationID.isDigest(rawValue) else { return nil }
            self.rawValue = rawValue
        }
    }

    let rawValue: String
    let scope: Scope

    init?(rawValue: String) {
        let pieces = rawValue.split(separator: ".", omittingEmptySubsequences: false)
        guard pieces.count == 2,
              let scope = Scope(rawValue: String(pieces[0])),
              Self.isDigest(String(pieces[1])) else {
            return nil
        }
        self.rawValue = rawValue
        self.scope = scope
    }

    static func journal(sessionID: String, correlationKey: String) -> Self? {
        func digest(_ value: String) -> String {
            SHA256.hash(data: Data(value.utf8)).prefix(12)
                .map { String(format: "%02x", $0) }.joined()
        }
        return Self(rawValue: "\(digest("codex-journal:\(sessionID)")).\(digest(correlationKey))")
    }

    private static func isDigest(_ value: String) -> Bool {
        value.utf8.count == 24
            && value.utf8.allSatisfy { byte in
                (0x30...0x39).contains(byte) || (0x61...0x66).contains(byte)
            }
    }
}
