"""Completion summaries: when an agent finishes a turn, read what it produced
and brief the user in about 100 words.

The recap is generated by the same Ultravox call (no second model): the
screen text is injected as a framed briefing the model must summarize aloud.
"""

from __future__ import annotations

import re
import time
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional

from .cmux_client import CmuxClient, CmuxError
from .events import AgentCompletion

MAX_SCREEN_CHARS = 6000
DEBOUNCE_S = 4.0  # collapse rapid Stop/SessionEnd pairs into one recap

SUMMARY_INSTRUCTIONS = (
    "[Agent turn completed. This is a system briefing, not the user speaking. "
    "Summarize aloud in at most 100 words what the coding agent just completed, "
    "based on the terminal text below. Structure it as: what was completed; "
    "takeaways; side notes; warnings (only if any). Speak naturally in short "
    "sentences, do not read code or paths verbatim, do not call any tool, and "
    "do not ask a question. If the text shows only a prompt with nothing "
    "completed, say one sentence saying the agent is waiting for input.]\n"
)


@dataclass
class SummaryRecord:
    seq: int
    source: str
    surface_id: Optional[str]
    briefing: str
    created_at: float = field(default_factory=time.time)


class CompletionSummarizer:
    def __init__(self, client: CmuxClient, *, enabled: bool = True, only_focused: bool = False) -> None:
        self.client = client
        self.enabled = enabled
        self.only_focused = only_focused
        self._last_by_surface: Dict[str, float] = {}
        self.history: List[SummaryRecord] = []

    async def briefing_for(self, completion: AgentCompletion) -> Optional[str]:
        """The text to inject into the call, or None to skip this event."""
        if not self.enabled:
            return None
        key = completion.surface_id or completion.workspace_id or "?"
        now = time.time()
        if now - self._last_by_surface.get(key, 0.0) < DEBOUNCE_S:
            return None
        self._last_by_surface[key] = now

        screen = await self._read_screen(completion.surface_id)
        if screen is None:
            return None
        where = await self._describe_surface(completion)
        header = f"Agent: {completion.source}. Location: {where}.\n"
        briefing = SUMMARY_INSTRUCTIONS + header + "--- terminal ---\n" + screen + "\n--- end ---"
        self.history.append(SummaryRecord(seq=completion.seq, source=completion.source, surface_id=completion.surface_id, briefing=briefing))
        del self.history[:-20]
        return briefing

    async def briefing_for_surface(self, surface_id: Optional[str], *, source: str = "manual") -> Optional[str]:
        """On-demand recap of one terminal (the app's Recap button). Never debounced, works even when disabled."""
        screen = await self._read_screen(surface_id)
        if screen is None:
            return None
        header = f"Requested by the user for the terminal they clicked. Agent: {source}.\n"
        briefing = SUMMARY_INSTRUCTIONS + header + "--- terminal ---\n" + screen + "\n--- end ---"
        self.history.append(SummaryRecord(seq=0, source=source, surface_id=surface_id, briefing=briefing))
        del self.history[:-20]
        return briefing

    async def _read_screen(self, surface_id: Optional[str]) -> Optional[str]:
        params: Dict[str, Any] = {"lines": 120}
        if surface_id:
            params["surface_id"] = surface_id
        try:
            res = await self.client.acall("surface.read_text", params) or {}
        except CmuxError:
            return None
        text = res.get("text")
        if text is None and res.get("base64"):
            import base64

            text = base64.b64decode(res["base64"]).decode("utf-8", errors="replace")
        return condense(text or "")

    async def _describe_surface(self, completion: AgentCompletion) -> str:
        try:
            rows = (await self.client.acall("workspace.list") or {}).get("workspaces") or []
        except CmuxError:
            rows = []
        for r in rows:
            if str(r.get("id")) == str(completion.workspace_id):
                return f'workspace "{r.get("title") or "?"}"'
        return "a workspace"


_ANSI = re.compile(r"\x1b\[[0-9;?]*[ -/]*[@-~]")
# Any line made only of braille spinner glyphs, bullets, box-drawing, or rule characters.
_SPINNER = re.compile(r"^[\s\u2800-\u28ff·•●○◐◑◒◓▪▫■□|/\\\-─━═│┃╭╮╰╯┏┓┗┛┌┐└┘]*$")


def condense(text: str, limit: int = MAX_SCREEN_CHARS) -> str:
    """Strip ANSI, drop blank/spinner/rule-only lines, collapse repeats, keep the tail."""
    out: List[str] = []
    prev = None
    for raw in _ANSI.sub("", text).splitlines():
        line = raw.rstrip()
        stripped = line.strip()
        if not stripped or _SPINNER.match(stripped):
            continue
        if stripped == prev:
            continue
        prev = stripped
        out.append(line)
    joined = "\n".join(out)
    return joined[-limit:] if len(joined) > limit else joined
