"""Completion summaries: when an agent finishes a turn, announce it, and, when
the user asks, read what it produced and brief them in about 100 words.

The recap is generated by the same Ultravox call (no second model): the
screen text is handed to the model (as a tool result) that it must summarize
aloud.
"""

from __future__ import annotations

import re
import time
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional

from .cmux_client import CmuxClient, CmuxError
from .events import AgentCompletion

MAX_SCREEN_CHARS = 6000
DEBOUNCE_S = 4.0  # collapse rapid Stop/SessionEnd pairs into one callout

SUMMARY_INSTRUCTIONS = (
    "[Agent turn completed. This is a system briefing, not the user speaking. "
    "Summarize aloud in at most 100 words what the coding agent just completed, "
    "based on the terminal text below: what was completed, takeaways, and "
    "warnings (only if any). Then end with exactly one concrete next step the "
    "user could send to that agent, phrased as \"Next, you could tell it to ...\". "
    "Speak naturally in short sentences, do not read code or paths verbatim, "
    "call no other tool, and do not ask a question. If the text shows only a "
    "prompt with nothing completed, say one sentence saying the agent is "
    "waiting for input.]\n"
)

AGENT_LABELS = {"claude": "Claude Code", "codex": "Codex", "opencode": "OpenCode", "gemini": "Gemini", "pi": "Pi"}


def callout_sentence(terminal_name: str) -> str:
    """The one sentence spoken the moment an agent finishes, anywhere."""
    return f"Terminal {terminal_name} is done. Would you like a summary?"


@dataclass
class SummaryRecord:
    seq: int
    source: str
    surface_id: Optional[str]
    briefing: str
    created_at: float = field(default_factory=time.time)


@dataclass
class FinishedAgent:
    """A completion announced to the user whose summary they have not asked for yet."""

    completion: AgentCompletion
    terminal_name: str
    workspace_title: str
    tab_title: str
    announced_at: float = field(default_factory=time.time)


class CompletionSummarizer:
    def __init__(self, client: CmuxClient, *, enabled: bool = True, only_focused: bool = False) -> None:
        self.client = client
        self.enabled = enabled
        self.only_focused = only_focused
        self._last_by_surface: Dict[str, float] = {}
        self.history: List[SummaryRecord] = []
        # Completions announced with "Terminal X is done. Would you like a
        # summary?", newest last. Popped when the user asks for the summary.
        self.pending: Dict[str, FinishedAgent] = {}

    # ------------------------------------------------------------- pending

    def defer(self, completion: AgentCompletion, *, terminal_name: str = "", workspace_title: str = "", tab_title: str = "") -> None:
        if completion.surface_id:
            self.pending.pop(completion.surface_id, None)  # re-insert so the newest is last
            self.pending[completion.surface_id] = FinishedAgent(completion, terminal_name, workspace_title, tab_title)

    def take_pending(self, surface_id: Optional[str] = None, workspace_id: Optional[str] = None) -> Optional[AgentCompletion]:
        """Pop the deferred completion for a surface, or, when only a workspace
        is known, the newest one in that workspace."""
        if surface_id and surface_id in self.pending:
            return self.pending.pop(surface_id).completion
        if workspace_id:
            for sid, item in reversed(list(self.pending.items())):
                if item.completion.workspace_id == workspace_id:
                    return self.pending.pop(sid).completion
        return None

    def take_by_name(self, target: Optional[str]) -> Optional[FinishedAgent]:
        """Pop the announced completion the user is asking about: the newest one
        when no name is given, otherwise the one whose terminal, tab, or
        workspace name matches the spoken words best."""
        if not self.pending:
            return None
        if not target or not target.strip():
            sid = next(reversed(self.pending))
            return self.pending.pop(sid)
        want = _spoken_key(target)
        best_sid, best_score = None, 0
        for sid, item in self.pending.items():
            for name in (item.terminal_name, item.tab_title, item.workspace_title):
                score = _name_overlap(want, _spoken_key(name))
                if score > best_score:
                    best_sid, best_score = sid, score
        if best_sid is None:
            return None
        return self.pending.pop(best_sid)

    # ------------------------------------------------------------- callout

    async def callout_for(self, completion: AgentCompletion) -> str:
        """The system notice the model must speak verbatim, as one sentence."""
        name, ws_title, tab_title = await self.terminal_name_for(completion)
        self.defer(completion, terminal_name=name, workspace_title=ws_title or "", tab_title=tab_title or "")
        return (
            "[Agent finished. This is a system notice, not the user speaking. Interrupt whatever you were saying and say exactly this one sentence: "
            f'"{callout_sentence(name)}" Then stop and call no tools. If the user answers yes, call summarize_agent.]'
        )

    async def terminal_name_for(self, completion: AgentCompletion) -> tuple[str, Optional[str], Optional[str]]:
        """How to name the finished terminal aloud: the workspace title, or
        "workspace tab" when that workspace holds more than one terminal."""
        ws_title, tab_title, terminals = None, None, 0
        try:
            tree = await self.client.acall("system.tree") or {}
            for window in tree.get("windows") or []:
                for w in window.get("workspaces") or []:
                    hit = False
                    count = 0
                    for pane in w.get("panes") or []:
                        for surf in pane.get("surfaces") or []:
                            if (surf.get("type") or "terminal") == "terminal":
                                count += 1
                            if str(surf.get("id")) == str(completion.surface_id):
                                hit = True
                                tab_title = surf.get("title")
                    if hit:
                        ws_title, terminals = w.get("title"), count
        except CmuxError:
            pass
        if not ws_title:
            return "unknown", None, tab_title
        if terminals > 1 and tab_title and tab_title != ws_title:
            return f"{ws_title} {tab_title}", ws_title, tab_title
        return ws_title, ws_title, tab_title

    # ------------------------------------------------------------ briefing

    async def briefing_for(self, completion: AgentCompletion) -> Optional[str]:
        """The text to inject into the call, or None to skip this event."""
        if not self.enabled:
            return None
        if not self.should_announce(completion):
            return None
        screen = await self._read_screen(completion.surface_id)
        if screen is None:
            return None
        where = await self._describe_surface(completion)
        header = f"Agent: {completion.source}. Location: {where}.\n"
        briefing = SUMMARY_INSTRUCTIONS + header + "--- terminal ---\n" + screen + "\n--- end ---"
        self.history.append(SummaryRecord(seq=completion.seq, source=completion.source, surface_id=completion.surface_id, briefing=briefing))
        del self.history[:-20]
        return briefing

    def should_announce(self, completion: AgentCompletion) -> bool:
        """Once per turn: cmux emits Stop and SessionEnd within a second of each other."""
        key = completion.surface_id or completion.workspace_id or "?"
        now = time.time()
        if now - self._last_by_surface.get(key, 0.0) < DEBOUNCE_S:
            return False
        self._last_by_surface[key] = now
        return True

    async def briefing_for_surface(self, surface_id: Optional[str], *, source: str = "manual") -> Optional[str]:
        """On-demand recap of one terminal (the Recap button, or "yes" after a
        callout). Never debounced, works even when disabled."""
        screen = await self._read_screen(surface_id)
        if screen is None:
            return None
        header = f"Requested by the user. Agent: {source}.\n"
        briefing = SUMMARY_INSTRUCTIONS + header + "--- terminal ---\n" + screen + "\n--- end ---"
        self.history.append(SummaryRecord(seq=0, source=source, surface_id=surface_id, briefing=briefing))
        del self.history[:-20]
        return briefing

    async def _read_screen(self, surface_id: Optional[str]) -> Optional[str]:
        params: Dict[str, Any] = {"lines": 120}
        if surface_id:
            params["surface_id"] = surface_id
        try:
            res = await self.client.acall("surface.read_text", params) or {}
        except CmuxError:
            return None
        text = res.get("text")
        if text is None and res.get("base64"):
            import base64

            text = base64.b64decode(res["base64"]).decode("utf-8", errors="replace")
        return condense(text or "")

    async def _describe_surface(self, completion: AgentCompletion) -> str:
        try:
            rows = (await self.client.acall("workspace.list") or {}).get("workspaces") or []
        except CmuxError:
            rows = []
        for r in rows:
            if str(r.get("id")) == str(completion.workspace_id):
                return f'workspace "{r.get("title") or "?"}"'
        return "a workspace"


_ANSI = re.compile(r"\x1b\[[0-9;?]*[ -/]*[@-~]")
# Any line made only of braille spinner glyphs, bullets, box-drawing, or rule characters.
_SPINNER = re.compile(r"^[\s\u2800-\u28ff·•●○◐◑◒◓▪▫■□|/\\\-─━═│┃╭╮╰╯┏┓┗┛┌┐└┘]*$")


_AGENT_LAUNCH = re.compile(r"(^|\s%\s|\$\s)(claude|codex|opencode|gemini)(\s|$)")

_WORD = re.compile(r"[a-z0-9]+")
_FILLER = {"the", "a", "an", "terminal", "workspace", "tab", "one", "that", "this", "it"}


def _spoken_key(text: str) -> set[str]:
    return {w for w in _WORD.findall((text or "").lower()) if w not in _FILLER}


def _name_overlap(want: set[str], have: set[str]) -> int:
    if not want or not have:
        return 0
    return len(want & have)


def focus_on_last_turn(text: str) -> str:
    """Keep only what follows the agent's most recent launch line, so a recap
    describes the latest turn rather than the whole scrollback."""
    lines = text.splitlines()
    for i in range(len(lines) - 1, -1, -1):
        if _AGENT_LAUNCH.search(lines[i]):
            tail = lines[i:]
            if len([l for l in tail if l.strip()]) >= 2:
                return "\n".join(tail)
            break
    return text


def condense(text: str, limit: int = MAX_SCREEN_CHARS) -> str:
    """Strip ANSI, keep the latest agent turn, drop blank/spinner/rule-only lines, collapse repeats."""
    out: List[str] = []
    prev = None
    for raw in focus_on_last_turn(_ANSI.sub("", text)).splitlines():
        line = raw.rstrip()
        stripped = line.strip()
        if not stripped or _SPINNER.match(stripped):
            continue
        if stripped == prev:
            continue
        prev = stripped
        out.append(line)
    joined = "\n".join(out)
    return joined[-limit:] if len(joined) > limit else joined
